version: '3'
services:
  fastchat-api:
    build: .
    ports:
      - "8000-8002:8000-8002"
    environment:
      - NGROK_AUTH_TOKEN=23baKlcVFtF3OkJtNrD6xExrYlI_7ZVM8X8z3bG6s3Zvt3Jgc
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]