version: '3'
services:
  fastchat-api:
    build: .
    ports:
      - "8000-8002:8000-8002"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]